# M3U Proxy Configuration Example
# Copy this file to config.toml and modify as needed

[database]
# Database connection URL
# Supported: sqlite://, postgres://, mysql://
url = "sqlite://./m3u-proxy.db"

# Maximum number of database connections
max_connections = 10

[web]
# Web server bind address
host = "0.0.0.0"

# Web server port
port = 8080

# Base URL for generating full URLs (logos, streams, etc.)
# This should be the public URL that clients will use to access the service
# Examples:
#   http://localhost:8080 (for local development)
#   https://m3u-proxy.example.com (for production with domain)
#   http://192.168.1.100:8080 (for local network access)
base_url = "http://localhost:8080"

[storage]
# Directory for M3U file storage
m3u_path = "./data/m3u"

# Directory for uploaded logos
uploaded_logo_path = "./data/logos/uploaded"

# Directory for cached logos
cached_logo_path = "./data/logos/cached"

# Number of proxy versions to keep (0 = only current)
proxy_versions_to_keep = 3

[ingestion]
# How often to update progress during channel processing (in number of channels)
# Lower values = more frequent updates but higher overhead
# Higher values = less frequent updates but better performance
progress_update_interval = 1000

# Whether to run missed scheduled refreshes immediately on startup
# If true, sources that missed their scheduled refresh will run immediately
# If false, sources will wait for their next scheduled time
run_missed_immediately = true

# Optional: Display configuration for EPG viewer and channel listings
[display]
# Local timezone for displaying times (default: UTC)
# Use IANA timezone names like "America/New_York", "Europe/London", etc.
local_timezone = "UTC"

# Optional: Channel similarity analysis configuration for EPG conflict resolution
[channel_similarity]
# Regex patterns to remove when comparing channels (these indicate channel variants, not different channels)
# These patterns help identify clones/variants that should share the same tvg-id
clone_patterns = [
    "(?i)\\b4K\\b",           # 4K quality indicator
    "(?i)\\bHD\\b",           # HD quality indicator
    "(?i)\\bSD\\b",           # SD quality indicator
    "(?i)\\bHEVC\\b",         # HEVC codec indicator
    "(?i)\\b720P?\\b",        # 720p quality
    "(?i)\\b1080P?\\b",       # 1080p quality
    "(?i)\\bUHD\\b",          # UHD quality
    "\\[|\\]|\\(|\\)",        # Remove brackets and parentheses
    "(?i)\\(SAT\\)",          # Satellite source indicator
    "(?i)\\(CABLE\\)",        # Cable source indicator
    "(?i)\\(IPTV\\)",         # IPTV source indicator
]

# Patterns that indicate timeshift channels (e.g., +1, +24 hour variants)
# Hours shift will be extracted from the first capture group (\d+)
timeshift_patterns = [
    "(?i)\\+(\\d+)",          # Matches +1, +24, etc.
    "(?i)\\+(\\d+)H",         # Matches +1H, +24H, etc.
]

# Minimum confidence threshold for considering channels as clones (0.0-1.0)
# Channels above this threshold should share the same tvg-id/channel id
# Higher values = more strict matching, lower values = more permissive
clone_confidence_threshold = 0.90
