# M3U Proxy Configuration Example
# Copy this file to config.toml and modify as needed

[database]
# Database connection URL
# Supported: sqlite://, postgres://, mysql://
url = "sqlite://./m3u-proxy.db"

# Maximum number of database connections
max_connections = 10

[web]
# Web server bind address
host = "0.0.0.0"

# Web server port
port = 8080

[storage]
# Directory for M3U file storage
m3u_path = "./data/m3u"

# Directory for uploaded logos
uploaded_logo_path = "./data/logos/uploaded"

# Directory for cached logos
cached_logo_path = "./data/logos/cached"

# Number of proxy versions to keep (0 = only current)
proxy_versions_to_keep = 3

[ingestion]
# How often to update progress during channel processing (in number of channels)
# Lower values = more frequent updates but higher overhead
# Higher values = less frequent updates but better performance
progress_update_interval = 1000

# Whether to run missed scheduled refreshes immediately on startup
# If true, sources that missed their scheduled refresh will run immediately
# If false, sources will wait for their next scheduled time
run_missed_immediately = true
