# M3U Proxy Configuration Example
# Copy this file to config.toml and modify as needed
# All values shown are defaults - uncomment and modify as needed

# ┌─────────────────────────────────────────────────────────────┐
# │                     DATABASE CONFIGURATION                 │
# └─────────────────────────────────────────────────────────────┘

[database]
# Database connection URL - supports SQLite, PostgreSQL, MySQL
url = "sqlite://./m3u-proxy.db"

# Maximum number of concurrent database connections
max_connections = 10

# Database batch size configuration for performance optimization
[database.batch_sizes]
# Maximum EPG channels per batch (must respect SQLite 32,766 variable limit)
# EPG channels have 9 fields, so 3600 * 9 = 32,400 variables (safe margin)
epg_channels = 3600

# Maximum EPG programs per batch (must respect SQLite 32,766 variable limit)  
# EPG programs have 18 fields, so 1800 * 18 = 32,400 variables (safe margin)
epg_programs = 1800

# Maximum stream channels to process in a single chunk
stream_channels = 500

# Database connection timeout for busy operations
busy_timeout = "30s"

# SQLite cache size for better performance
cache_size = "64MB"

# WAL autocheckpoint interval (pages)
wal_autocheckpoint = 1000

# ┌─────────────────────────────────────────────────────────────┐
# │                      WEB SERVER CONFIGURATION              │
# └─────────────────────────────────────────────────────────────┘

[web]
# Web server bind address (0.0.0.0 = all interfaces, 127.0.0.1 = localhost only)
host = "0.0.0.0"

# Web server port
port = 8080

# Base URL for generating full URLs (logos, streams, etc.)
# This should match the public URL clients use to access the service
# Examples: http://localhost:8080, https://m3u-proxy.example.com, http://192.168.1.100:8080
base_url = "http://localhost:8080"

# HTTP request timeout for client connections
request_timeout = "30s"

# Maximum size for HTTP requests (affects file uploads)
max_request_size = "10MB"

# ┌─────────────────────────────────────────────────────────────┐
# │                     STORAGE CONFIGURATION                  │
# └─────────────────────────────────────────────────────────────┘

[storage]
# Directory for generated M3U playlist files
m3u_path = "./data/m3u"

# Directory for user-uploaded channel logos
uploaded_logo_path = "./data/logos/uploaded"

# Directory for automatically cached/downloaded logos
cached_logo_path = "./data/logos/cached"

# Number of previous proxy versions to retain (0 = only current)
proxy_versions_to_keep = 3

# Optional: Custom temporary file directory (None = system default)
# temp_path = "./data/temp"

# Automatically clean orphaned logo entries when paths change
clean_orphan_logos = true

# ┌─────────────────────────────────────────────────────────────┐
# │                   INGESTION CONFIGURATION                  │
# └─────────────────────────────────────────────────────────────┘

[ingestion]
# Progress update frequency during channel processing (lower = more frequent updates)
progress_update_interval = 1000

# Run missed scheduled refreshes immediately on startup
run_missed_immediately = true

# ┌─────────────────────────────────────────────────────────────┐
# │                    DISPLAY CONFIGURATION                   │
# └─────────────────────────────────────────────────────────────┘

[display]
# Local timezone for EPG viewer and channel listings
# Use IANA timezone names: America/New_York, Europe/London, Asia/Tokyo, etc.
local_timezone = "UTC"

# ┌─────────────────────────────────────────────────────────────┐
# │               DATA MAPPING ENGINE CONFIGURATION            │
# └─────────────────────────────────────────────────────────────┘

[data_mapping_engine]
# Special characters for regex precheck filtering optimization
# These characters trigger fast-path matching before full regex evaluation
precheck_special_chars = "+-@#$%&*=<>!~`€£{}[]."

# Minimum literal string length for precheck optimization
# Strings shorter than this won't be used for precheck (0 = disable)
minimum_literal_length = 2

# ┌─────────────────────────────────────────────────────────────┐
# │               PROXY GENERATION CONFIGURATION               │
# └─────────────────────────────────────────────────────────────┘

[proxy_generation]
# Enable detailed memory usage tracking and reporting
enable_memory_tracking = true

# Enable performance profiling (adds overhead but provides timing details)
enable_profiling = false

# Memory management for proxy generation
[proxy_generation.memory]
# Maximum memory usage in MB (None = unlimited)
# System switches to smaller batches when approaching this limit
max_memory_mb = 512

# Number of channels to process per batch
# Smaller = less memory, larger = better performance
batch_size = 1000

# Enable parallel processing (faster but uses more memory)
enable_parallel_processing = true

# Memory usage check frequency (items processed between checks)
memory_check_interval = 100

# Warning threshold as fraction of max memory (0.0-1.0)
warning_threshold = 0.8

# EPG generation settings
[proxy_generation.epg]
# Include programs that have already ended
include_past_programs = false

# Days of future EPG data to include
days_ahead = 7

# Days of past EPG data to include  
days_behind = 1

# Remove duplicate programs with same title and time
deduplicate_programs = true

# Maximum programs per channel (None = unlimited)
# Limiting this significantly reduces memory usage
max_programs_per_channel = 1000

# Source timezone for EPG normalization (None = auto-detect)
# Only used when converting times to UTC
# source_timezone = "UTC"

# ┌─────────────────────────────────────────────────────────────┐
# │                  FILE MANAGER CONFIGURATION                │
# └─────────────────────────────────────────────────────────────┘

[file_manager]
# Base directory for temporary and cache files
# base_directory = "/tmp/m3u-proxy"

# File category configurations with retention policies
[file_manager.categories.proxy_output]
subdirectory = "proxy-output"
retention_duration = "30d"
time_match = "LastAccess"
enabled = true

[file_manager.categories.temp]
subdirectory = "temp"
retention_duration = "5m"
time_match = "LastAccess"
enabled = true

# ┌─────────────────────────────────────────────────────────────┐
# │                    PIPELINE CONFIGURATION                  │
# └─────────────────────────────────────────────────────────────┘

[pipeline]
# Maximum memory usage in MB before spilling to disk
max_memory_mb = 512

# Pipeline suspension duration when errors occur
suspension_duration = "5m"

# Logo processing batch size for memory management
logo_batch_size = 1000

# Channel processing batch size for efficiency
channel_batch_size = 100

# EPG processing batch size for memory management
epg_batch_size = 1000

# Maximum retry attempts for failed operations
max_retries = 3

# ┌─────────────────────────────────────────────────────────────┐
# │                    METRICS CONFIGURATION                   │
# └─────────────────────────────────────────────────────────────┘

[metrics]
# Data retention periods for access logs and statistics
# Use format: 1d, 7d, 30d, 1h, 2h, etc.

# Raw access log retention period
raw_log_retention = "7d"

# Hourly aggregated statistics retention
hourly_stats_retention = "30d"

# Daily aggregated statistics retention
daily_stats_retention = "365d"

# Client session timeout for tracking
session_timeout = "15s"

# Cleanup task run interval
housekeeper_interval = "1m"

# ┌─────────────────────────────────────────────────────────────┐
# │                 RELAY SYSTEM CONFIGURATION                 │
# └─────────────────────────────────────────────────────────────┘

[relay]
# FFmpeg command path for relay operations
# Can be full path (/usr/bin/ffmpeg) or command name (ffmpeg)
# System searches $PATH if not a full path
ffmpeg_command = "ffmpeg"

# Cyclic buffer configuration for multi-client streaming
[relay.buffer]
# Maximum buffer size in bytes (50MB default)
max_buffer_size = 52428800

# Maximum number of chunks to keep in memory
max_chunks = 1000

# How long to keep chunks in memory (seconds)
chunk_timeout_seconds = 60

# Timeout for slow clients (seconds)
client_timeout_seconds = 30

# Buffer cleanup interval (seconds)
cleanup_interval_seconds = 5

# Enable spilling to disk when buffer is full
enable_file_spill = false

# Maximum file spill size in bytes (500MB default)
max_file_spill_size = 524288000

# FFprobe command path for stream analysis
# Used for relay stream probing and optimization
ffprobe_command = "ffprobe"

# Stream analysis duration for FFmpeg probing
analyzeduration = "10s"

# Stream probe size for FFmpeg analysis
probesize = "10MB"

# ┌─────────────────────────────────────────────────────────────┐
# │               RETENTION POLICY CONFIGURATION               │
# └─────────────────────────────────────────────────────────────┘

# File retention and cleanup intervals
# Use format: 5m, 1h, 4h, 1d, 30d, etc.

[storage]
# M3U file retention period
m3u_retention = "30d"

# M3U cleanup check interval
m3u_cleanup_interval = "4h"

# Cached logo retention period
cached_logo_retention = "90d"

# Cached logo cleanup check interval
cached_logo_cleanup_interval = "12h"

# Temporary file retention period
temp_retention = "5m"

# Temporary file cleanup check interval
temp_cleanup_interval = "1m"

# Pipeline artifact retention period
pipeline_retention = "10m"

# Pipeline cleanup check interval
pipeline_cleanup_interval = "2m"

# ┌─────────────────────────────────────────────────────────────┐
# │               OPERATIONAL CONFIGURATION                    │
# └─────────────────────────────────────────────────────────────┘

[operational]
# Log buffer size for in-memory logging
log_buffer_size = 200

# Similarity threshold for expression matching (0.0-1.0)
similarity_threshold = 0.60

# Progress reporting intervals for UI responsiveness
[operational.progress_intervals]
# Logo progress batch interval (log every N batches)
logo_progress_interval = 10

# Channel debug interval (log every N channels)
channel_debug_interval = 1000

# EPG progress log interval (log every N programs)
epg_progress_interval = 10000

# ┌─────────────────────────────────────────────────────────────┐
# │                 FEATURE FLAGS CONFIGURATION                │
# └─────────────────────────────────────────────────────────────┘

[features.flags]
# Enable debug logging in the frontend web interface
debug-frontend = true

# Example feature flags (can be added/removed via settings page):
# experimental-ui = false
# advanced-video-player = true

# Feature-specific configuration can be added here:
# [features.config.some-feature]
# option1 = "value"
# option2 = 123