# M3U Proxy Configuration Example
# Copy this file to config.toml and modify as needed

[database]
# Database connection URL
# Supported: sqlite://, postgres://, mysql://
url = "sqlite://./m3u-proxy.db"

# Maximum number of database connections
max_connections = 10

[web]
# Web server bind address
host = "0.0.0.0"

# Web server port
port = 8080

# Base URL for generating full URLs (logos, streams, etc.)
# This should be the public URL that clients will use to access the service
# Examples:
#   http://localhost:8080 (for local development)
#   https://m3u-proxy.example.com (for production with domain)
#   http://192.168.1.100:8080 (for local network access)
base_url = "http://localhost:8080"

[storage]
# Directory for M3U file storage
m3u_path = "./data/m3u"

# Directory for uploaded logos
uploaded_logo_path = "./data/logos/uploaded"

# Directory for cached logos
cached_logo_path = "./data/logos/cached"

# Number of proxy versions to keep (0 = only current)
proxy_versions_to_keep = 3

# Automatically clean up orphaned logo database entries when uploaded_logo_path changes
clean_orphan_logos = true

[ingestion]
# How often to update progress during channel processing (in number of channels)
# Lower values = more frequent updates but higher overhead
# Higher values = less frequent updates but better performance
progress_update_interval = 1000

# Whether to run missed scheduled refreshes immediately on startup
# If true, sources that missed their scheduled refresh will run immediately
# If false, sources will wait for their next scheduled time
run_missed_immediately = true

# Optional: Display configuration for EPG viewer and channel listings
[display]
# Local timezone for displaying times (default: UTC)
# Use IANA timezone names like "America/New_York", "Europe/London", etc.
local_timezone = "UTC"

# Optional: Data mapping engine optimization configuration
[data_mapping_engine]
# Special characters used for regex precheck filtering
# These characters are considered significant enough to use as first-pass filters
# Set to empty string "" to disable special character precheck
# Default: "+-@#$%&*=<>!~`€£{}[]."
precheck_special_chars = "+-@#$%&*=<>!~`€£{}[]."

# Minimum length required for literal strings in regex precheck
# Strings shorter than this will not be used for precheck filtering
# Set to 0 to disable literal string precheck entirely
# Default: 2
minimum_literal_length = 2

# Proxy generation configuration
[proxy_generation]
# Enable detailed memory tracking and reporting during generation
enable_memory_tracking = true

# Enable performance profiling (adds overhead but provides detailed timing)
enable_profiling = false

# Enable file spilling for memory pressure relief (requires sandboxed file manager)
enable_file_spilling = true

# Memory management configuration
[proxy_generation.memory]
# Maximum memory usage in MB for proxy generation (None = unlimited)
# When this limit is approached, the system will process in smaller batches
# Set to a value appropriate for your system (e.g., 512 for 512MB)
max_memory_mb = 512

# Number of channels to process in each batch
# Smaller batches use less memory but may be slower
# Larger batches are faster but use more memory
batch_size = 1000

# Enable parallel processing where possible
# Uses more memory but can be significantly faster on multi-core systems
enable_parallel_processing = true

# How often to check memory usage (in number of processed items)
# Lower values = more frequent checks but higher overhead
memory_check_interval = 100

# Memory warning threshold (0.0-1.0)
# System will log warnings when memory usage exceeds this percentage of max_memory_mb
warning_threshold = 0.8

# Memory strategy preset for handling pressure situations
# Options: "default", "conservative", "aggressive", "temp_file_based", "custom"
strategy_preset = "conservative"

# EPG generation configuration
[proxy_generation.epg]
# Include programs that have already ended
include_past_programs = false

# Number of days of future EPG data to include
days_ahead = 7

# Number of days of past EPG data to include
days_behind = 1

# Normalize all EPG times to UTC (recommended for consistency)
normalize_to_utc = true

# Remove duplicate programs with same title and time
deduplicate_programs = true

# Maximum number of programs per channel (None = unlimited)
# Limiting this can significantly reduce memory usage and generation time
max_programs_per_channel = 1000

# Source timezone for EPG normalization (None = auto-detect from EPG source)
# Only used when normalize_to_utc = true
# Use IANA timezone names like "America/New_York", "Europe/London", etc.
# source_timezone = "UTC"

# File manager configuration for temporary and cached files
[file_manager]
# Base directory for all file storage (default: system temp directory)
base_directory = "/tmp/m3u-proxy"

# Configuration for different file categories
# Each category can have its own retention policy and cleanup settings

# Note: preview category removed - temp category is used for both temp and preview operations
# Note: logo category removed - logo storage is managed via storage.cached_logo_path and storage.uploaded_logo_path

[file_manager.categories.proxy_output]
subdirectory = "proxy-output"
# Keep generated proxy files for 30 days
retention_duration = "30days"
time_match = "LastAccess"
enabled = true
# cleanup_interval = "4h"

[file_manager.categories.temp]
subdirectory = "temp"
# Temporary files for memory spilling and preview operations
retention_duration = "5m"
time_match = "LastAccess"
enabled = true
# cleanup_interval = "1m"

# Note: cache category removed - no longer needed

# Sandboxed file manager configuration for secure operations
[sandboxed_file_manager]
# Enable sandboxed file operations (recommended for security)
enabled = true

# Security settings
[sandboxed_file_manager.security]
# Validate file paths to prevent directory traversal attacks
validate_paths = true
# Check for and prevent symlink-based sandbox escapes
validate_symlinks = true
# Restrict file operations to allowed file types
restrict_file_types = true

# File type validation configuration
# If restrict_file_types is true, only these MIME types will be allowed
# If empty or not specified, all file types are allowed
allowed_mime_types = [
    "application/vnd.apple.mpegurl", # M3U playlists
    "application/x-mpegurl",         # M3U playlists (alternative)
    "application/xml",               # XML files
    "text/xml",                      # XML files (alternative)
    "text/plain",                    # Plain text files
    "application/json",              # JSON files
    "image/png",                     # PNG images
    "image/jpeg",                    # JPEG images
    "image/gif",                     # GIF images
    "image/webp",                    # WebP images
    "image/svg+xml",                 # SVG images
]

# Maximum bytes to read from files for magic number detection
max_detection_bytes = 8192

# Whether to enable custom file type matchers (for special formats like M3U)
enable_custom_matchers = true

# Performance settings for file operations
[sandboxed_file_manager.performance]
# Maximum file size for spill operations (in MB)
max_spill_file_size_mb = 100
# Maximum number of concurrent file operations
max_concurrent_operations = 10
# Buffer size for file I/O operations (in KB)
io_buffer_size_kb = 64

# Native Pipeline Configuration
[pipeline]
# Maximum memory usage in MB before spilling to disk (default: 512MB)
max_memory_mb = 512
