# Example configuration showing data mapping precheck customization

[database]
url = "sqlite://./m3u-proxy.db"
max_connections = 10

# Database batch size configuration for bulk inserts
[database.batch_sizes]
# Maximum number of EPG channels to insert in a single batch
# Each channel has 9 fields, so batch_size * 9 must be <= SQLite variable limit (32,766)
# Default: 3600 (= 32,400 variables, safe margin)
epg_channels = 3600

# Maximum number of EPG programs to insert in a single batch  
# Each program has 17 fields, so batch_size * 17 must be <= SQLite variable limit (32,766)
# Default: 1900 (= 32,300 variables, safe margin)
epg_programs = 1900

# Maximum number of stream channels to process in a single chunk
# Not limited by SQLite variables, optimized for performance
# Default: 1000
stream_channels = 1000

[web]
host = "0.0.0.0"
port = 8080
base_url = "http://localhost:8080"

[storage]
m3u_path = "./data/m3u"
uploaded_logo_path = "./data/logos/uploaded" 
cached_logo_path = "./data/logos/cached"
proxy_versions_to_keep = 3

[ingestion]
progress_update_interval = 1000
run_missed_immediately = true

[display]
local_timezone = "UTC"

# Data mapping precheck configuration
[data_mapping]
# Special characters used for regex precheck filtering
# These characters are considered significant enough to use as first-pass filters
# Default: "+-@#$%&*=<>!~`€£{}[]"
precheck_special_chars = "+-@#$%&*=<>!~`€£{}[]"

# Minimum length required for literal strings in regex precheck
# Strings shorter than this will not be used for precheck filtering
# Default: 2
minimum_literal_length = 2

[channel_similarity]
clone_patterns = [
    "(?i)\\b4K\\b",
    "(?i)\\bHD\\b", 
    "(?i)\\bSD\\b",
    "(?i)\\bHEVC\\b",
    "(?i)\\b720P?\\b",
    "(?i)\\b1080P?\\b",
    "(?i)\\bUHD\\b",
    "\\[|\\]|\\(|\\)",
    "(?i)\\(SAT\\)",
    "(?i)\\(CABLE\\)",
    "(?i)\\(IPTV\\)"
]
timeshift_patterns = ["(?i)\\+(\\d+)", "(?i)\\+(\\d+)H"]
clone_confidence_threshold = 0.90