apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m3u-proxy-data
  namespace: m3u-proxy
  labels:
    app: m3u-proxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # Optional: specify storage class
  # storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m3u-proxy-config
  namespace: m3u-proxy
  labels:
    app: m3u-proxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi