//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "channel_epg_mapping")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub stream_channel_id: Uuid,
    pub epg_channel_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub mapping_type: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::StreamChannelId",
        to = "super::channels::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Channels,
    #[sea_orm(
        belongs_to = "super::epg_channels::Entity",
        from = "Column::EpgChannelId",
        to = "super::epg_channels::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EpgChannels,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::epg_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EpgChannels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
