//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "epg_sources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub source_type: String,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    #[sea_orm(column_type = "Text")]
    pub update_cron: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_timezone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub time_offset: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub last_ingested_at: Option<DateTime<Utc>>,
    pub is_active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::epg_programs::Entity")]
    EpgPrograms,
    #[sea_orm(has_many = "super::proxy_epg_sources::Entity")]
    ProxyEpgSources,
}

impl Related<super::epg_programs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EpgPrograms.def()
    }
}

impl Related<super::proxy_epg_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProxyEpgSources.def()
    }
}

impl Related<super::stream_proxies::Entity> for Entity {
    fn to() -> RelationDef {
        super::proxy_epg_sources::Relation::StreamProxies.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::proxy_epg_sources::Relation::EpgSources.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
