//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod channel_epg_mapping;
pub mod channel_relay_configs;
pub mod channels;
pub mod data_mapping_rules;
pub mod epg_channels;
pub mod epg_programs;
pub mod epg_sources;
pub mod filters;
pub mod last_known_codecs;
pub mod linked_xtream_sources;
pub mod logo_assets;
pub mod migration_notes;
pub mod proxy_epg_sources;
pub mod proxy_filters;
pub mod proxy_generations;
pub mod proxy_sources;
pub mod relay_events;
pub mod relay_profiles;
pub mod relay_runtime_status;
pub mod stream_proxies;
pub mod stream_sources;
