//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "proxy_epg_sources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub proxy_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub epg_source_id: Uuid,
    pub priority_order: i32,
    pub created_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::epg_sources::Entity",
        from = "Column::EpgSourceId",
        to = "super::epg_sources::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EpgSources,
    #[sea_orm(
        belongs_to = "super::stream_proxies::Entity",
        from = "Column::ProxyId",
        to = "super::stream_proxies::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StreamProxies,
}

impl Related<super::epg_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EpgSources.def()
    }
}

impl Related<super::stream_proxies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StreamProxies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
