//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use uuid::Uuid;
use crate::models::StreamSourceType;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "stream_sources")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub source_type: StreamSourceType,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub max_concurrent_streams: i32,
    #[sea_orm(column_type = "Text")]
    pub update_cron: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub field_map: Option<String>,
    pub ignore_channel_numbers: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub last_ingested_at: Option<DateTime<Utc>>,
    pub is_active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channels::Entity")]
    Channels,
    #[sea_orm(has_many = "super::linked_xtream_sources::Entity")]
    LinkedXtreamSources,
    #[sea_orm(has_many = "super::proxy_sources::Entity")]
    ProxySources,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::linked_xtream_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LinkedXtreamSources.def()
    }
}

impl Related<super::proxy_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProxySources.def()
    }
}

impl Related<super::stream_proxies::Entity> for Entity {
    fn to() -> RelationDef {
        super::proxy_sources::Relation::StreamProxies.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::proxy_sources::Relation::StreamSources.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
