name: Release

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Parallel job 1: Build binaries for multiple platforms
  build-binaries:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: false
            archive_name: m3u-proxy-linux-x86_64.tar.gz

          # Linux ARM64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            archive_name: m3u-proxy-linux-arm64.tar.gz

          # macOS x86_64
          - target: x86_64-apple-darwin
            os: macos-latest
            cross: false
            archive_name: m3u-proxy-macos-x86_64.tar.gz

          # macOS ARM64 (Apple Silicon)
          - target: aarch64-apple-darwin
            os: macos-latest
            cross: false
            archive_name: m3u-proxy-macos-arm64.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Get version and update source files
        run: |
          VERSION=$(just get-version)
          just set-version "$VERSION"
          echo "Building with version: $VERSION"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-
            ${{ runner.os }}-cargo-

      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-${{ matrix.target }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-target-

      - name: Install cross compilation tools (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install cross (if needed)
        if: matrix.cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        if: matrix.cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Build natively
        if: "!matrix.cross"
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          if command -v strip >/dev/null 2>&1; then
            strip target/${{ matrix.target }}/release/m3u-proxy
          elif command -v ${{ matrix.target }}-strip >/dev/null 2>&1; then
            ${{ matrix.target }}-strip target/${{ matrix.target }}/release/m3u-proxy
          fi

      - name: Create release archive
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release

          # Create archive with binary and additional files
          mkdir -p m3u-proxy-release
          cp m3u-proxy m3u-proxy-release/

          # Copy additional files
          cd ../../..
          cp README.md m3u-proxy-release/ 2>/dev/null || echo "README.md not found"
          cp LICENSE m3u-proxy-release/ 2>/dev/null || echo "LICENSE not found"
          cp config.example.toml m3u-proxy-release/config.toml 2>/dev/null || echo "config.example.toml not found"

          # Create the archive
          tar czf ${{ matrix.archive_name }} -C target/${{ matrix.target }}/release m3u-proxy-release

          # Verify archive was created
          ls -la ${{ matrix.archive_name }}

      - name: Generate checksums
        shell: bash
        run: |
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum ${{ matrix.archive_name }} > ${{ matrix.archive_name }}.sha256
          elif command -v shasum >/dev/null 2>&1; then
            shasum -a 256 ${{ matrix.archive_name }} > ${{ matrix.archive_name }}.sha256
          fi
          cat ${{ matrix.archive_name }}.sha256

      - name: Install Syft
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Generate SBOM with Syft
        shell: bash
        run: |
          syft target/${{ matrix.target }}/release/m3u-proxy -o spdx-json=sbom-${{ matrix.target }}.spdx.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: m3u-proxy-${{ matrix.target }}
          path: |
            ${{ matrix.archive_name }}
            ${{ matrix.archive_name }}.sha256
            sbom-${{ matrix.target }}.spdx.json
          retention-days: 7

      - name: Upload to release (if triggered by release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.archive_name }}
          asset_name: ${{ matrix.archive_name }}
          asset_content_type: application/gzip

      - name: Upload checksum to release (if triggered by release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.archive_name }}.sha256
          asset_name: ${{ matrix.archive_name }}.sha256
          asset_content_type: text/plain

      - name: Upload SBOM to release (if triggered by release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sbom-${{ matrix.target }}.spdx.json
          asset_name: sbom-${{ matrix.target }}.spdx.json
          asset_content_type: application/json

  # Parallel job 2: Build and push container images using your just commands
  build-container:
    name: Build and Push Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Get version
        id: version
        run: |
          VERSION=$(just get-version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building container with version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container using just
        run: just build-container-versioned

      - name: Push container using just
        run: just push-container

      - name: Generate container SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
          format: spdx-json
          output-file: container-sbom-${{ steps.version.outputs.version }}.spdx.json

      - name: Upload container SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-sbom-${{ steps.version.outputs.version }}
          path: container-sbom-${{ steps.version.outputs.version }}.spdx.json
          retention-days: 30

      - name: Upload container SBOM to release (if triggered by release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: container-sbom-${{ steps.version.outputs.version }}.spdx.json
          asset_name: container-sbom-${{ steps.version.outputs.version }}.spdx.json
          asset_content_type: application/json

  # Job 3: Update release notes (runs after both parallel jobs)
  update-release:
    name: Update Release Notes
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [build-binaries, build-container]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Get version
        id: version
        run: |
          VERSION=$(just get-version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, using all commits"
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            echo "Comparing with previous tag: $PREV_TAG"
            COMMITS=$(git log ${PREV_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Create changelog content
          CHANGELOG="## What's Changed

          $COMMITS

          ## Container Images

          - \`ghcr.io/${{ github.repository }}:latest\`
          - \`ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}\`
          - \`ghcr.io/${{ github.repository }}:release\`

          ## Installation

          ### Binary Installation
          1. Download the appropriate binary for your platform from the assets below
          2. Extract the archive: \`tar -xzf m3u-proxy-*.tar.gz\`
          3. Run the binary: \`./m3u-proxy-release/m3u-proxy\`

          ### Container Installation
          \`\`\`bash
          # Using just commands (recommended for development)
          just build-container-versioned
          just push-container

          # Or pull from registry
          docker run -p 8080:8080 -v ./data:/app/data ghcr.io/${{ github.repository }}:latest
          \`\`\`

          ## Security

          This release includes Software Bill of Materials (SBOM) files for both binaries and container images to ensure supply chain security and compliance."

          echo "$CHANGELOG" > release_notes.md

      - name: Update release
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const release_notes = fs.readFileSync('release_notes.md', 'utf8');

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: release_notes
            });
